-- SCENTAI first-party analytics
-- Run once in the Supabase SQL editor.

create table if not exists public.scentai_analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  occurred_at timestamptz not null,
  session_key text not null,
  event text not null check (
    event in ('page_view', 'consultation_start', 'product_open', 'merchant_clickout')
  ),
  product_id text null,
  source text null,
  created_at timestamptz not null default now()
);

create index if not exists scentai_analytics_events_occurred_at_idx
  on public.scentai_analytics_events (occurred_at desc);

create index if not exists scentai_analytics_events_session_key_idx
  on public.scentai_analytics_events (session_key);

create index if not exists scentai_analytics_events_event_idx
  on public.scentai_analytics_events (event);

alter table public.scentai_analytics_events enable row level security;

-- No public RLS policies are created.
-- Production writes use the server-side service-role key from Render.
