-- SCENTAI first-party analytics
-- Run once in the Supabase SQL editor.

create table if not exists public.scentai_analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  occurred_at timestamptz not null,
  session_key text not null,
  event text not null check (
    event in (
      'page_view',
      'consultation_start',
      'product_open',
      'merchant_clickout',
      'catalog_search',
      'catalog_no_results'
    )
  ),
  product_id text null,
  source text null,
  search_term text null check (
    search_term is null or char_length(search_term) <= 80
  ),
  result_count integer null check (
    result_count is null or result_count >= 0
  ),
  created_at timestamptz not null default now()
);


alter table public.scentai_analytics_events
  add column if not exists search_term text null,
  add column if not exists result_count integer null;

alter table public.scentai_analytics_events
  drop constraint if exists scentai_analytics_events_event_check;

alter table public.scentai_analytics_events
  add constraint scentai_analytics_events_event_check
  check (
    event in (
      'page_view',
      'consultation_start',
      'product_open',
      'merchant_clickout',
      'catalog_search',
      'catalog_no_results'
    )
  );

alter table public.scentai_analytics_events
  drop constraint if exists scentai_analytics_events_result_count_check;

alter table public.scentai_analytics_events
  add constraint scentai_analytics_events_result_count_check
  check (result_count is null or result_count >= 0);

alter table public.scentai_analytics_events
  drop constraint if exists scentai_analytics_events_search_term_length_check;

alter table public.scentai_analytics_events
  add constraint scentai_analytics_events_search_term_length_check
  check (search_term is null or char_length(search_term) <= 80);

create index if not exists scentai_analytics_events_occurred_at_idx
  on public.scentai_analytics_events (occurred_at desc);

create index if not exists scentai_analytics_events_session_key_idx
  on public.scentai_analytics_events (session_key);

create index if not exists scentai_analytics_events_event_idx
  on public.scentai_analytics_events (event);

alter table public.scentai_analytics_events enable row level security;

-- No public RLS policies are created.
-- Production writes use the server-side service-role key from Render.


create index if not exists scentai_analytics_events_search_idx
  on public.scentai_analytics_events (event, search_term)
  where event in ('catalog_search', 'catalog_no_results');

create or replace view public.scentai_catalog_search_demand
with (security_invoker = true)
as
select
  search_term,
  count(*) filter (
    where event = 'catalog_search'
  ) as search_events,
  count(*) filter (
    where event = 'catalog_no_results'
  ) as no_result_events,
  count(distinct session_key) as unique_sessions,
  round(avg(result_count)::numeric, 2) as avg_result_count,
  max(occurred_at) as last_searched_at
from public.scentai_analytics_events
where event in ('catalog_search', 'catalog_no_results')
  and search_term is not null
group by search_term;

create or replace view public.scentai_product_engagement
with (security_invoker = true)
as
select
  product_id,
  count(*) filter (
    where event = 'product_open'
  ) as product_opens,
  count(*) filter (
    where event = 'merchant_clickout'
  ) as merchant_clickouts,
  count(distinct session_key) filter (
    where event = 'product_open'
  ) as opening_sessions,
  count(distinct session_key) filter (
    where event = 'merchant_clickout'
  ) as clickout_sessions,
  max(occurred_at) as last_event_at
from public.scentai_analytics_events
where product_id is not null
  and event in ('product_open', 'merchant_clickout')
group by product_id;

