/**
 * German presentation labels for DUFYND fragrance notes.
 *
 * Source catalog note names stay unchanged because they also drive matching,
 * icon classification and provenance. Public UI uses noteLabel() instead.
 */
export const NOTE_LABELS_DE: Record<string, string> = {
  "absinthe wormwood": "Wermut (Absinth)",
  "akigalawood": "Akigalawood",
  "aldehydes": "Aldehyde",
  "amber": "Amber",
  "ambergris": "Ambra",
  "amberwood": "Amberholz",
  "ambrette": "Ambrette",
  "ambrette seed": "Ambrettesamen",
  "ambrofix": "Ambrofix",
  "ambrox": "Ambrox",
  "ambroxan": "Ambroxan",
  "apple": "Apfel",
  "bergamot": "Bergamotte",
  "birch": "Birke",
  "black cherry": "Schwarzkirsche",
  "black tea from china": "Schwarzer Tee aus China",
  "blackcurrant": "Schwarze Johannisbeere",
  "bourbon vanilla": "Bourbon-Vanille",
  "calabrian bergamot": "Kalabrische Bergamotte",
  "cardamom": "Kardamom",
  "carnation": "Gartennelke",
  "cashmeran": "Cashmeran",
  "cashmere": "Kaschmir",
  "cedar": "Zeder",
  "cedarwood": "Zedernholz",
  "ceylon cinnamon": "Ceylon-Zimt",
  "chestnut": "Kastanie",
  "chinese black tea": "Chinesischer Schwarztee",
  "cinnamon": "Zimt",
  "citron": "Zedratzitrone",
  "citrus": "Zitrus",
  "clary sage": "Muskatellersalbei",
  "cocoa leaf": "Kakaoblatt",
  "coriander": "Koriander",
  "coumarin": "Cumarin",
  "crystal amber": "Kristall-Amber",
  "damask rose": "Damaszener Rose",
  "dry woods": "Trockene Hölzer",
  "elemi": "Elemi",
  "georgywood": "Georgywood",
  "geranium": "Geranie",
  "ginger": "Ingwer",
  "grapefruit": "Grapefruit",
  "green apple": "Grüner Apfel",
  "guaiac wood": "Guajakholz",
  "haitian vetiver": "Haitianischer Vetiver",
  "honey": "Honig",
  "incense": "Weihrauch",
  "indian sandalwood": "Indisches Sandelholz",
  "iris": "Iris",
  "italian orange": "Italienische Orange",
  "jasmine": "Jasmin",
  "jasmine sambac": "Sambac-Jasmin",
  "labdanum": "Labdanum",
  "lavender": "Lavendel",
  "leather": "Leder",
  "lemon": "Zitrone",
  "light woods": "Helle Hölzer",
  "lily of the valley": "Maiglöckchen",
  "lime": "Limette",
  "magnolia": "Magnolie",
  "mahonia": "Mahonie",
  "mandarin": "Mandarine",
  "mandarin orange": "Mandarine",
  "maté": "Maté",
  "melon": "Melone",
  "mint": "Minze",
  "moss": "Moos",
  "musk": "Moschus",
  "neroli": "Neroli",
  "nigerian ginger": "Nigerianischer Ingwer",
  "nutmeg": "Muskatnuss",
  "oak moss": "Eichenmoos",
  "omani frankincense": "Omanischer Weihrauch",
  "opium": "Opium",
  "orange blossom": "Orangenblüte",
  "orris root": "Iriswurzel",
  "oud": "Oud",
  "pale iris": "Helle Iris",
  "papyrus": "Papyrus",
  "patchouli": "Patschuli",
  "pepper": "Pfeffer",
  "petit grain": "Petitgrain",
  "pineapple": "Ananas",
  "pineapple accord": "Ananas-Akkord",
  "pink musk": "Rosa Moschus",
  "pink pepper": "Rosa Pfeffer",
  "praline": "Praline",
  "provençal lavender": "Provenzalischer Lavendel",
  "rose": "Rose",
  "rosemary": "Rosmarin",
  "sage": "Salbei",
  "sandalwood": "Sandelholz",
  "sicilian cedar": "Sizilianische Zeder",
  "sicilian orange": "Sizilianische Orange",
  "spices": "Gewürze",
  "tea": "Tee",
  "thai basil": "Thailändisches Basilikum",
  "timut pepper": "Timut-Pfeffer",
  "tobacco": "Tabak",
  "tonka bean": "Tonkabohne",
  "tunisian neroli": "Tunesisches Neroli",
  "vanilla": "Vanille",
  "vanilla orchid": "Vanilleorchidee",
  "vetiver": "Vetiver",
  "violet": "Veilchen",
  "white floral": "Weiße Blüten",
  "white magnolia": "Weiße Magnolie",
  "white musk": "Weißer Moschus",
  "woody notes": "Holzige Noten",
};

export function noteLabel(note: string): string {
  return NOTE_LABELS_DE[note.trim().toLocaleLowerCase("en-US")] || note;
}
