/**
 * German presentation labels for DUFYND fragrance notes.
 *
 * Source catalog note names stay unchanged because they also drive matching,
 * icon classification and provenance. Public UI uses noteLabel() instead.
 */
export const NOTE_LABELS_DE: Record<string, string> = {
  "absinthe wormwood": "Wermut (Absinth)",
  "akigalawood": "Akigalawood",
  "aldehydes": "Aldehyde",
  "amber": "Amber",
  "ambergris": "Ambra",
  "amberwood": "Amberholz",
  "ambrette": "Ambrette",
  "ambrette seed": "Ambrettesamen",
  "ambrofix": "Ambrofix",
  "ambrox": "Ambrox",
  "ambroxan": "Ambroxan",
  "apple": "Apfel",
  "bergamot": "Bergamotte",
  "birch": "Birke",
  "black cherry": "Schwarzkirsche",
  "black tea from china": "Schwarzer Tee aus China",
  "blackcurrant": "Schwarze Johannisbeere",
  "bourbon vanilla": "Bourbon-Vanille",
  "calabrian bergamot": "Kalabrische Bergamotte",
  "cardamom": "Kardamom",
  "carnation": "Gartennelke",
  "cashmeran": "Cashmeran",
  "cashmere": "Kaschmir",
  "cedar": "Zeder",
  "cedarwood": "Zedernholz",
  "ceylon cinnamon": "Ceylon-Zimt",
  "chestnut": "Kastanie",
  "chinese black tea": "Chinesischer Schwarztee",
  "cinnamon": "Zimt",
  "citron": "Zedratzitrone",
  "citrus": "Zitrus",
  "clary sage": "Muskatellersalbei",
  "cocoa leaf": "Kakaoblatt",
  "coriander": "Koriander",
  "coumarin": "Cumarin",
  "crystal amber": "Kristall-Amber",
  "cypress": "Zypresse",
  "damask rose": "Damaszener Rose",
  "dry woods": "Trockene Hölzer",
  "elemi": "Elemi",
  "georgywood": "Georgywood",
  "geranium": "Geranie",
  "ginger": "Ingwer",
  "grapefruit": "Grapefruit",
  "green apple": "Grüner Apfel",
  "guaiac wood": "Guajakholz",
  "haitian vetiver": "Haitianischer Vetiver",
  "honey": "Honig",
  "incense": "Weihrauch",
  "indian sandalwood": "Indisches Sandelholz",
  "iris": "Iris",
  "italian orange": "Italienische Orange",
  "jasmine": "Jasmin",
  "jasmine sambac": "Sambac-Jasmin",
  "labdanum": "Labdanum",
  "lavender": "Lavendel",
  "leather": "Leder",
  "lemon": "Zitrone",
  "light woods": "Helle Hölzer",
  "lily of the valley": "Maiglöckchen",
  "lime": "Limette",
  "magnolia": "Magnolie",
  "mahonia": "Mahonie",
  "mandarin": "Mandarine",
  "mandarin orange": "Mandarine",
  "maté": "Maté",
  "melon": "Melone",
  "mint": "Minze",
  "moss": "Moos",
  "musk": "Moschus",
  "neroli": "Neroli",
  "nigerian ginger": "Nigerianischer Ingwer",
  "nutmeg": "Muskatnuss",
  "oak moss": "Eichenmoos",
  "omani frankincense": "Omanischer Weihrauch",
  "opium": "Opium",
  "orange blossom": "Orangenblüte",
  "orris root": "Iriswurzel",
  "oud": "Oud",
  "pale iris": "Helle Iris",
  "papyrus": "Papyrus",
  "patchouli": "Patschuli",
  "pepper": "Pfeffer",
  "petit grain": "Petitgrain",
  "pineapple": "Ananas",
  "pineapple accord": "Ananas-Akkord",
  "pink musk": "Rosa Moschus",
  "pink pepper": "Rosa Pfeffer",
  "praline": "Praline",
  "provençal lavender": "Provenzalischer Lavendel",
  "raspberry": "Himbeere",
  "rose": "Rose",
  "rosemary": "Rosmarin",
  "sage": "Salbei",
  "sandalwood": "Sandelholz",
  "sicilian cedar": "Sizilianische Zeder",
  "sicilian orange": "Sizilianische Orange",
  "spices": "Gewürze",
  "tea": "Tee",
  "thai basil": "Thailändisches Basilikum",
  "timut pepper": "Timut-Pfeffer",
  "tobacco": "Tabak",
  "tonka bean": "Tonkabohne",
  "tunisian neroli": "Tunesisches Neroli",
  "vanilla": "Vanille",
  "vanilla orchid": "Vanilleorchidee",
  "vetiver": "Vetiver",
  "violet": "Veilchen",
  "white floral": "Weiße Blüten",
  "white magnolia": "Weiße Magnolie",
  "white musk": "Weißer Moschus",
  "woody notes": "Holzige Noten",
  "almond": "Mandel",
  "ambergris accord": "Ambra-Akkord",
  "ambermax": "AmberMax",
  "ambery woods": "Amberige Hölzer",
  "ambrofix amber": "Ambrofix-Amber",
  "arabian jasmine": "Arabischer Jasmin",
  "atlas cedar": "Atlaszeder",
  "benzoin": "Benzoe",
  "bitter almond": "Bittermandel",
  "bitter orange leaves": "Bitterorangenblätter",
  "black leather": "Schwarzes Leder",
  "black pepper": "Schwarzer Pfeffer",
  "blue ginger": "Blauer Ingwer",
  "bourbon": "Bourbon",
  "bourbon geranium": "Bourbon-Geranie",
  "brown sugar": "Brauner Zucker",
  "cade oil": "Cadeöl",
  "candied apple": "Kandierter Apfel",
  "caramel": "Karamell",
  "chestnut accord": "Kastanien-Akkord",
  "cistus absolute": "Zistrosen-Absolue",
  "clove": "Gewürznelke",
  "cocoa": "Kakao",
  "coconut": "Kokosnuss",
  "coffee": "Kaffee",
  "damask rose essence": "Damaszener-Rosenessenz",
  "date": "Dattel",
  "davana": "Davana",
  "dry woody notes": "Trockene Holznoten",
  "ethyl maltol": "Ethylmaltol",
  "everlasting essence": "Immortellenessenz",
  "floral notes": "Blumige Noten",
  "fougère accord": "Fougère-Akkord",
  "frangipani": "Frangipani",
  "frankincense": "Weihrauch",
  "freesia": "Freesie",
  "french lavender": "Französischer Lavendel",
  "fruity fresh top": "Fruchtig-frische Kopfnote",
  "geranium absolute": "Geranien-Absolue",
  "green accord": "Grüner Akkord",
  "green notes": "Grüne Noten",
  "guaiac wood oil": "Guajakholzöl",
  "hay": "Heu",
  "hazelnut": "Haselnuss",
  "hedione": "Hedione",
  "honey/tobacco facets": "Honig-/Tabakfacetten",
  "italian bergamot": "Italienische Bergamotte",
  "italian lemon": "Italienische Zitrone",
  "italian mandarin": "Italienische Mandarine",
  "jasmine flowers": "Jasminblüten",
  "jasmine grandiflorum": "Jasmin Grandiflorum",
  "jasmine tea": "Jasmintee",
  "juniper": "Wacholder",
  "lavandin heart": "Lavandin-Herznote",
  "leather accord": "Leder-Akkord",
  "lemon essence": "Zitronenessenz",
  "liquorice": "Lakritz",
  "lotus": "Lotus",
  "lychee": "Litschi",
  "mahogany": "Mahagoni",
  "marine notes": "Maritime Noten",
  "marshmallow": "Marshmallow",
  "milk": "Milch",
  "mint oil": "Minzöl",
  "mirabelle": "Mirabelle",
  "modern woods": "Moderne Hölzer",
  "moroccan orange blossom": "Marokkanische Orangenblüte",
  "myrrh": "Myrrhe",
  "nectarine blossom": "Nektarinenblüte",
  "neroli bud": "Neroli-Knospe",
  "oakmoss": "Eichenmoos",
  "orange": "Orange",
  "orange blossom absolute": "Orangenblüten-Absolue",
  "orchid": "Orchidee",
  "orris": "Iriswurzel",
  "osmanthus": "Osmanthus",
  "pear": "Birne",
  "peony": "Pfingstrose",
  "peru balsam resinoid": "Perubalsam-Resinoid",
  "petitgrain": "Petitgrain",
  "pine": "Kiefer",
  "pink apple": "Rosa Apfel",
  "pomegranate": "Granatapfel",
  "red berries": "Rote Beeren",
  "red pepper berries": "Rote Pfefferbeeren",
  "rhubarb": "Rhabarber",
  "roasted tonka bean": "Geröstete Tonkabohne",
  "rose water": "Rosenwasser",
  "rum": "Rum",
  "saffron": "Safran",
  "sage essence": "Salbeiessenz",
  "sambac jasmine": "Sambac-Jasmin",
  "strawberry": "Erdbeere",
  "structured woods": "Strukturierte Hölzer",
  "sugar": "Zucker",
  "tahitian vanilla": "Tahitianische Vanille",
  "tobacco leaf": "Tabakblatt",
  "tuberose": "Tuberose",
  "turkish rose": "Türkische Rose",
  "vanilla accord": "Vanille-Akkord",
  "vanilla facets": "Vanillefacetten",
  "vanilla trio": "Vanille-Trio",
  "vanillin": "Vanillin",
  "vetiver essence": "Vetiveressenz",
  "violet leaf absolute": "Veilchenblatt-Absolue",
  "virginia cedar": "Virginia-Zeder",
  "white amber": "Weißer Amber",
  "white florals": "Weiße Blüten",
  "white gardenia": "Weiße Gardenie",
  "woody accord": "Holziger Akkord",
  "woody mineral accord": "Holzig-mineralischer Akkord",
  "ylang-ylang": "Ylang-Ylang",
  "ylang-ylang essence": "Ylang-Ylang-Essenz",
};

export function noteLabel(note: string): string {
  return NOTE_LABELS_DE[note.trim().toLocaleLowerCase("en-US")] || note;
}
